### ISSUE TITLE
[MVP] OpenFeature Provider

### ISSUE THREAD

**Issue by osbornm** [Hyphen/openfeature-provider-javascript-web#1]
## Overview
We are going to leverage [OpenFeature](https://openfeature.dev/) as our SDK for Toggle. OpenFeature uses a provider model that allows 3rd parties to have a common interface for their SDKs. The goal of this task is to create an MVP version of our OpenFeature Provider. Subsequent releases will add performance and quality of development improvements. 

## Tasks
- [x] Implements Provider interface (get{X}Value)
	- [x] Validates context object
	- [x] Handles incorrect typing (asking for a bool value from a string value) 
- [x] Implements a hyphenClient with multiple URL support (custom URL and then our default URL)
- [x] Implements a caching layer (TTL of 30 seconds, but make it a constant/configurable)
- [x] Greater than 90% code coverage
- [x] Contains example of how to consume the provider
	- [x] These should exist in an examples folder
	- [x] These should be excluded from any packaged content (NPM package, etc.)
- [x] Has a README that 
	- [x] First and foremost explains how to use the provider
	- [x] Contains information on how to develop the provider
- [x] License File
- [x] Issue templates
- [x] Contribution markdown file
- [x] CI/CD Pipeline
	- [x] PR pipeline (build, lint, test)
	- [x] Release Pipeline (publish to package manager)
- [x] First pass documentation for docs site

## References
* https://openfeature.dev/docs/reference/concepts/provider
* https://github.com/Hyphen/Horizon
